### ISSUE TITLE
add notebook for stsdas.analysis.dither

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#45]
Dither and drizzling tasks.

@SaraOgaz, can you examine how much of this exists in AstroDrizzle?  I haven't done much imaging, so i'm not sure if Astrodrizzle was basically all of this moved out of IRAF, or if there are still things here that users may need.

- avshift
- blot
- blot_mask
- cdriz
- cor_shft
- crossdriz
- deriv
- dr2gpar
- driz_cr
- drizzle
- dunlearn
- filename
- fileroot
- gprep
- imextreme
- loop_blot
- loop_driz
- mask_head
- minv
- offsets
- ogsky
- precor
- qzap
- rotfind
- shiftfind
- sky
- tranback
- traxy
- wblot
- wcs2dr
- wdrizzle
- wfpc2_chips
- wtranback
- wtraxy

**Comment by stsci-hack** [comment]
The DrizzlePac package implements much of this functionality, but primarily integrated into larger tasks, rather than the more atomic tasks available in the iraf drizzle package.  A meeting to discuss what is in place in DrizzlePac would be helpful to identify the scope of work for replacing all the functionality provided by the IRAF tasks and to determine whether all of these need to be replaced in the first place.

**Comment by hcferguson** [comment]
@stsci-hack , @justincely This also overlaps with the goals of the [reproject](http://reproject.readthedocs.io/en/stable/) package, which might be the place where the drizzle algorithm would best live in Astropy.

However the full workflow requires three other essential tasks:

- determine shifts and rotations
- determine sky levels
- create a mask of cosmic-rays and other bad pixels

These currently live in DrizzlePac, but should be made modular if they aren't easily callable and modifiable.  There are obviously other ways to do these in python, but  DrizzlePac is a good starting point.

The tasks of transferring coordinates coordinates to and from rectified un-rectified frames (blot, traxy, tranback) have been largely written in python (by Nadia and Mihai), but I'm not sure where they currently live. They probably ultimately belong in reproject as well. They require the that the distortion info is in the WCS. That is *definitely* the way we want to go for the future but we may need to think about backwards compatibility with IDC tables and SIP and the like. Or (perhaps better) small tasks that will update WCSs so that reproject and other codes can do their thing.

**Comment by stsci-hack** [comment]
The updatewcs task in STWCS will integrate IDC table inputs into the image headers as SIP coefficients, and we have already provided support for all HST (legacy and active) imagers with this code.  Many of the atomic tasks in DrizzlePac can be provided with user-interfaces to run them more easily.  In fact, determining sky levels is already a stand-alone general package, skymatch.  Determining the shifts and rotations can be done using 'tweakreg' based on catalogs provided by the end user already, whereas some of the more atomic functions of determining the shifts is provided by functions called by tweakreg.  One such task would be 'xyxymatch' found in the stsci.image(?) as a direct replacement for IRAF's 'xyxymatch' task.  There were plans to make additional callable interfaces for many of the functions in DrizzlePac, so it should not take too much effort to develop some of them.

**Comment by SaraOgaz** [comment]
Close call for now, will eventually open a new one at https://github.com/spacetelescope/stak-notebooks/issues
